name: My Workflow

on:
  push:
    branches:
      - '*'

jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: bkresaj/my_private_repo:nrf_smart_door_lock
      options: --volume ${{ github.workspace }}:/workdir/project
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build
      run: |
        echo "Building code."
        cd /workdir/project
        ./scripts/build.py

  Test:
    runs-on: ubuntu-latest
    container:
      image: bkresaj/my_private_repo:nrf_smart_door_lock
      options: --volume ${{ github.workspace }}:/workdir/project
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test
      run: |
        echo "Running unit tests."
        cd /workdir/project
        ./scripts/run_unit_tests.py

    - uses: actions/upload-artifact@v3
      with:
        name: test_log
        path: /workdir/project/smart_door_lock/build/tests/Testing/Temporary/LastTest.log

  Static-analysis:
    runs-on: ubuntu-latest
    container:
      image: bkresaj/my_private_repo:nrf_smart_door_lock
      options: --volume ${{ github.workspace }}:/workdir/project
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Static analysis
      run: | 
        echo "Running static analysis."
        cd /workdir/project
        ./scripts/run_cpp_checker.py
    
    - uses: actions/upload-artifact@v3
      with:
        name: cppcheck_log
        path: /workdir/project/output/report.log
